apiVersion: v1
kind: Service
metadata:
  name: flask-app-lb
  labels:
    app: flask-app-lb
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: flask-app
